name = "domain-parkour"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Cloudflare KV namespace for storing domain configurations securely
# Setup: wrangler kv:namespace create "DOMAIN_CONFIGS"
# Then replace domain-parkour-kv with the actual namespace ID from the output
[[kv_namespaces]]
binding = "DOMAIN_CONFIGS"
id = "domain-parkour-kv"
# For preview environment:
# preview_id = "domain-parkour-kv-preview"

# Configure routes for multiple domains
# Each domain will automatically use its configuration from KV or environment variables
# routes = [
#   { pattern = "cdn.farm", zone_name = "cdn.farm" },
#   { pattern = "example.com", zone_name = "example.com" },
#   { pattern = "anotherdomain.com", zone_name = "anotherdomain.com" }
# ]

# CONFIGURATION HIERARCHY (in priority order):
# 1. Cloudflare KV (RECOMMENDED) - Store domain configs in DOMAIN_CONFIGS namespace
#    - Supports multiple domains easily
#    - Can be updated without redeployment
#    - Example: wrangler kv:key put --namespace-id=xxx "example.com" '{"title":"..."}'
#
# 2. Environment Variables (OPTIONAL OVERRIDES)
#    - Use for temporary overrides or when KV is not available
#    - NOT recommended as primary storage for domain configs
#
# 3. Cloudflare Secrets (FOR TRULY SENSITIVE DATA ONLY)
#    - Use Dashboard > Workers > Settings > Secrets
#    - Only for API keys, tokens, credentials that need encryption at rest
#    - Domain configs (emails, pricing) are fine in KV - it's already secure

# Environment variable examples (uncomment to use):

# Option 1: Full domain config as JSON string (fallback if not in KV)
# [vars]
# CDN_FARM_CONFIG = '{"title":"Premium CDN Domain","salePrice":"25,000 USD","contactEmail":"contact@example.com"}'

# Option 2: Individual property overrides (override specific properties from KV)
# [vars]
# CDN_FARM_TITLE = "CDN Farm - Premium Domain"
# CDN_FARM_SALE_PRICE = "30,000 USD"
# CDN_FARM_CONTACT_EMAIL = "buy@cdn.farm"
#
# EXAMPLE_COM_TITLE = "Example.com - Available Now"
# EXAMPLE_COM_SALE_PRICE = "60,000 USD"
# EXAMPLE_COM_CONTACT_EMAIL = "sales@example.com"

# WARNING: Do NOT commit sensitive API keys or credentials in wrangler.toml to public repos!

